version: '3.8'

services:
  mongodb-router-1:
    container_name: mongodb-router-1
    image: mongo:$MONGODB_VERSION
    command: mongos --configdb $CONFIG_RS_NAME/$SHARD_IP_1:10001,$CONFIG_RS_NAME/$SHARD_IP_2:10002 --port 27017
    depends_on:
      - mongodb-config-1
      - mongodb-shard-1
      - mongodb-shard-2
    ports:
      - 30000:27017

  mongodb-config-1:
    container_name: mongodb-config-1
    image: mongo:$MONGODB_VERSION
    command: mongod --configsvr --replSet $CONFIG_RS_NAME --dbpath /data/db --port 27017
    ports:
      - 10001:27017
    volumes:
      - config-1:/data/db

  mongodb-shard-1:
    container_name: mongodb-shard-1
    image: mongo:$MONGODB_VERSION
    command: mongod --shardsvr --replSet $SHARD_NAME_1 --dbpath /data/db --port 27017
    ports:
      - 20001:27017
    volumes:
      - shard-1:/data/db

  mongodb-shard-2:
    container_name: mongodb-shard-2
    image: mongo:$MONGODB_VERSION
    command: mongod --shardsvr --replSet $SHARD_NAME_2 --dbpath /data/db --port 27017
    ports:
      - 20002:27017
    volumes:
      - shard-2:/data/db

volumes:
  config-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/config-1
  shard-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/shard-1
  shard-2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/shard-2