version: '3.8'

services:
  mongodb-config-1:
    container_name: mongodb-config-1
    image: mongo:$MONGODB_VERSION
    command: mongod --configsvr --replSet $CONFIG_RS_NAME --dbpath /data/db --port 27017
    ports:
      - $CONFIG_RS_1_PORT:27017
    volumes:
      - ./data/config-1:/data/db